export const disputeCategories = [
  "ORDER_NOT_RECEIVED", "WRONG_PRODUCT", "MISSING_ITEM", "DAMAGED_PRODUCT", "INCORRECT_QUANTITY", "DEFECTIVE_PRODUCT", "ORDER_CANCELLATION", "DELIVERY_PROBLEM", "OTHER_ORDER_ISSUE",
  "SERVICE_NOT_COMPLETED", "LATE_SERVICE", "SERVICE_QUALITY", "BOOKING_PROBLEM", "INCORRECT_SERVICE", "PROPERTY_SERVICE_DAMAGE", "OTHER_SERVICE_ISSUE",
  "DUPLICATE_PAYMENT", "INCORRECT_AMOUNT", "PAYMENT_NOT_RECOGNIZED", "PAYMENT_PENDING", "PAYMENT_ORDER_NOT_UPDATED", "REFUND_MISSING", "PARTIAL_REFUND_DISAGREEMENT", "CHARGEBACK_RELATED",
  "SUSPECTED_PRODUCT_DEFECT", "SAFETY_COMPLAINT", "LABELING_COMPLAINT", "INGREDIENT_CONCERN", "ADVERSE_REACTION", "PACKAGING_PROBLEM", "SUSPECTED_CONTAMINATION", "RECALL_RELATED",
  "COMMISSION_DISPUTE", "ATTRIBUTION_DISPUTE", "PAYOUT_DISPUTE", "PROHIBITED_ACTIVITY", "ACCOUNT_RESTRICTION",
  "PRIVACY_COMPLAINT", "PERSONAL_DATA_REQUEST", "CONSENT_ISSUE", "ACCOUNT_DATA_ACCESS",
  "B2B_SERVICE", "CONTRACT_ISSUE", "INVOICE_DISPUTE", "BUSINESS_DELIVERY", "OTHER_BUSINESS_COMPLAINT",
] as const;

export type DisputeCategory = typeof disputeCategories[number];
export const disputeStatuses = ["OPEN", "ACKNOWLEDGED", "INVESTIGATING", "WAITING_FOR_INFORMATION", "RESOLUTION_PROPOSED", "RESOLVED", "CLOSED", "ESCALATED", "EXTERNAL_REVIEW_REQUIRED", "EXTERNAL_ACTION_REQUIRED", "CANCELLED", "DUPLICATE", "REJECTED"] as const;
export type DisputeStatus = typeof disputeStatuses[number];
export const resolutionTypes = ["EXPLANATION", "REPLACEMENT", "REFUND", "PARTIAL_REFUND", "STORE_CREDIT", "SERVICE_REDO", "CANCELLATION", "RETURN_AUTHORIZATION", "RECALL_ESCALATION", "ACCOUNT_CORRECTION", "COMMISSION_CORRECTION", "NO_ACTION", "EXTERNAL_ESCALATION"] as const;
export type ResolutionType = typeof resolutionTypes[number];

const transitions: Record<DisputeStatus, readonly DisputeStatus[]> = {
  OPEN: ["ACKNOWLEDGED", "CANCELLED", "DUPLICATE", "REJECTED"], ACKNOWLEDGED: ["INVESTIGATING", "WAITING_FOR_INFORMATION", "ESCALATED"],
  INVESTIGATING: ["WAITING_FOR_INFORMATION", "RESOLUTION_PROPOSED", "ESCALATED", "EXTERNAL_REVIEW_REQUIRED"], WAITING_FOR_INFORMATION: ["INVESTIGATING", "CANCELLED", "ESCALATED"],
  RESOLUTION_PROPOSED: ["RESOLVED", "INVESTIGATING", "ESCALATED"], RESOLVED: ["CLOSED", "INVESTIGATING"], CLOSED: ["INVESTIGATING"],
  ESCALATED: ["INVESTIGATING", "EXTERNAL_REVIEW_REQUIRED", "EXTERNAL_ACTION_REQUIRED", "RESOLVED"], EXTERNAL_REVIEW_REQUIRED: ["EXTERNAL_ACTION_REQUIRED", "INVESTIGATING", "RESOLVED"], EXTERNAL_ACTION_REQUIRED: ["RESOLVED", "INVESTIGATING"],
  CANCELLED: [], DUPLICATE: [], REJECTED: [],
};

export function canTransition(from: DisputeStatus, to: DisputeStatus): boolean { return transitions[from].includes(to); }